### ISSUE TITLE
Cannot instantiate actor from imported module

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#668]
It is not possible to instantiate actors from imported modules!

```
kll@Boxy:~/terastream/acton/compiler/test/actonc/regressions/import_actor$ ~/terastream/acton/dist/bin/actonc build
Compiling foo.act for release

******************** Compilation error
Module foo does not export 'Bar$newact'
kll@Boxy:~/terastream/acton/compiler/test/actonc/regressions/import_actor$ 
```

I committed this regression in #666, so simply try to build that for a reproduction

**Comment by plajjan** [comment]
@nordlander is this similar to the not-possible-to-instantiate classes or different?

This one is not as critical for me, but if it's of similar character and easily fixed...!?

**Comment by nordlander** [comment]
Hmm, where has the example gone? There's no `test/actonc/regressions/` directory anymore...

**Comment by plajjan** [comment]
test/regression_auto/import... I think

**Comment by nordlander** [comment]
Problem fixed by PR #731. The test case still fails, though, seemingly because of a bad root argument in the test config. Leaving the issue open for that reason (for @plajjan  to fix!).

**Comment by plajjan** [comment]
Test case now working after #737 fixes.
