### ISSUE TITLE
Telemetrify no longer compiles with https://github.com/actonlang/acton/pull/1599

### ISSUE THREAD

**Issue by ddjoh** [actonlang/acton#1602]
### Acton Version

0.18.3.20231211.15.46.36

### Steps to Reproduce and Observed Behavior

Clone `https://github.com/telemetrify-collector/telemetrify`. Build acton code with `make`.

First error is:
```
ERROR: Error when compiling telemetrify.common.mod module: Type error

    |
367 |            if self[i] != other[i]:
    |               ^^^^
The type of self does not implement __builtin__.Indexed[_, _]
```

### Expected Behavior

Compilation to succeed as prior to https://github.com/actonlang/acton/pull/1599.
