### ISSUE TITLE
Cannot instantiate actor; considered abstract due to explicit type signature

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#670]
I added a regression / reproduction case in #669. Whenever there is a separate type signature in an actor, it is considered abstract

```
kll@Boxy:~/terastream/acton/compiler/test/actonc/regressions/abstract_actor_from_type_signature$ ~/terastream/acton/dist/bin/actonc build 

******************** Compilation error
 10:9-11
   |
10 |    f = Foo()
   |        ^^^
Abstract actor cannot be instantiated: Foo

kll@Boxy:~/terastream/acton/compiler/test/actonc/regressions/abstract_actor_from_type_signature$ 
```

code:
```

actor Foo():
    # actonc will interpret this type signature to mean the actor is abstract - clearly wrong
    # If we remove the type signature, this program works
    hello : action() -> None
    def hello():
        print("Hello World!")

actor main(env):
    f = Foo()
    f.hello()
    await async env.exit(0)
```

**Comment by nordlander** [comment]
I've disabled the check, it's fundamentally broken with the current deactorizer hackery.

But we also need to rethink the notion of "abstract" actors altogether. Since actors don't support inheritance I think what we're really after here is the ability to denote an actor interface (a type) as something separate from an actor implementation. Whether that type should be a protocol or an immutable class, and how the connection between interface and implementation should be expressed, must be analyzed carefully.
