### ISSUE TITLE
Error compiling isinstance checks

### ISSUE THREAD

**Issue by ddjoh** [actonlang/acton#1120]
### Acton Version

0.14.1.20221125.15.37.1

### Steps to Reproduce

Compile the following with actonc version v0.13.1 or newer:
```
def foo(x: value) -> bool:
    return isinstance(x, int)
```

### Expected Behavior

Success!

### Actual Behavior

```
Building project in /home/ddjoh/workspaces/act-test-1
  Compiling mod1.act for release
ERROR: internal compiler error: compilation of generated C code failed
NOTE: this is likely a bug in actonc, please report this at:
NOTE: https://github.com/actonlang/acton/issues/new?template=ice.yaml
NOTE: acton 0.14.1.20221125.15.37.1 compiled by ghc 8.10 on linux x86_64
NOTE: cc: 0.10.0
cc stdout:

cc stderr:
act-test-1/out/types/mod1.c:3:12: error: use of undeclared identifier '$int$new$methods'
    return $ISINSTANCE(x, $int$new);
           ^
/home/ddjoh/workspaces/acton/dist/builtin/common.h:35:65: note: expanded from macro '$ISINSTANCE'
                               while($c && $c != ($Super$class)&$T ## $methods) $c = $c->$superclass; \
                                                                ^
<scratch space>:37:1: note: expanded from here
$int$new$methods
^
1 error generated.

```

**Comment by ddjoh** [comment]
This compiles successfully with v0.13.0.

**Comment by sydow** [comment]
This compiles correctly with acton 0.14.2.20230122.17.4.1
