### ISSUE TITLE
Improve type error for missing argument (regression after #1609)

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1610]
#1609 regressed in type error for missing arguments, see https://github.com/actonlang/acton/pull/1609/files#diff-ade64a3c6f02a7c6d2466dad27669124eb3bf1a6b4f8a5ace52873c62889defb. We used to get the call site but now it only points to the definition.

Before:

```
|
4 |a = f(3)
  |    ^^^^


  |
1 |def f(x,y):
  |    ^
Type incompatibility between definition of and call of f (too few arguments in call)
f is inferred to have a type of the form [A(Plus)] => _(A, A) -> A
```

Now:
```
  |
1 |def f(x,y):
  |        ^
Keyword element 'y' is not found
```

This is after #1609 but not sure if it's on @nordlander or @sydow to fix.

**Comment by sydow** [comment]
This is clearly on me. Next week...

**Comment by sydow** [comment]
Fixed by #1637
